USE [My Database]
GO

UPDATE [dbo].[My Table Name]
   SET FIPS = CASE
					WHEN ([STATE_CODE] = 'AK') THEN '02'
					WHEN ([STATE_CODE] = 'AL') THEN '01'
					WHEN ([STATE_CODE] = 'AR') THEN '05'
					WHEN ([STATE_CODE] = 'AS') THEN '60'
					WHEN ([STATE_CODE] = 'AZ') THEN '04'
					WHEN ([STATE_CODE] = 'CA') THEN '06'
					WHEN ([STATE_CODE] = 'CO') THEN '08'
					WHEN ([STATE_CODE] = 'CT') THEN '09'
					WHEN ([STATE_CODE] = 'DC') THEN '11'
					WHEN ([STATE_CODE] = 'DE') THEN '10'
					WHEN ([STATE_CODE] = 'FL') THEN '12'
					WHEN ([STATE_CODE] = 'GA') THEN '13'
					WHEN ([STATE_CODE] = 'GU') THEN '66'
					WHEN ([STATE_CODE] = 'HI') THEN '15'
					WHEN ([STATE_CODE] = 'IA') THEN '19'
					WHEN ([STATE_CODE] = 'ID') THEN '16'
					WHEN ([STATE_CODE] = 'IN') THEN '18'
					WHEN ([STATE_CODE] = 'KS') THEN '20'
					WHEN ([STATE_CODE] = 'KY') THEN '21'
					WHEN ([STATE_CODE] = 'LA') THEN '22'
					WHEN ([STATE_CODE] = 'MA') THEN '25'
					WHEN ([STATE_CODE] = 'MD') THEN '24'
					WHEN ([STATE_CODE] = 'ME') THEN '23'
					WHEN ([STATE_CODE] = 'MI') THEN '26'
					WHEN ([STATE_CODE] = 'MN') THEN '27'
					WHEN ([STATE_CODE] = 'MO') THEN '29'
					WHEN ([STATE_CODE] = 'MS') THEN '28'
					WHEN ([STATE_CODE] = 'MT') THEN '30'
					WHEN ([STATE_CODE] = 'NC') THEN '37'
					WHEN ([STATE_CODE] = 'ND') THEN '38'
					WHEN ([STATE_CODE] = 'NE') THEN '31'
					WHEN ([STATE_CODE] = 'NH') THEN '33'
					WHEN ([STATE_CODE] = 'NJ') THEN '34'
					WHEN ([STATE_CODE] = 'NM') THEN '35'
					WHEN ([STATE_CODE] = 'NV') THEN '32'
					WHEN ([STATE_CODE] = 'NY') THEN '36'
					WHEN ([STATE_CODE] = 'OH') THEN '39'
					WHEN ([STATE_CODE] = 'OK') THEN '40'
					WHEN ([STATE_CODE] = 'OR') THEN '41'
					WHEN ([STATE_CODE] = 'PA') THEN '42'
					WHEN ([STATE_CODE] = 'PR') THEN '72'
					WHEN ([STATE_CODE] = 'RI') THEN '44'
					WHEN ([STATE_CODE] = 'SC') THEN '45'
					WHEN ([STATE_CODE] = 'SD') THEN '46'
					WHEN ([STATE_CODE] = 'TN') THEN '47'
					WHEN ([STATE_CODE] = 'TX') THEN '48'
					WHEN ([STATE_CODE] = 'UT') THEN '49'
					WHEN ([STATE_CODE] = 'VA') THEN '51'
					WHEN ([STATE_CODE] = 'VI') THEN '78'
					WHEN ([STATE_CODE] = 'VT') THEN '50'
					WHEN ([STATE_CODE] = 'WA') THEN '53'
					WHEN ([STATE_CODE] = 'WI') THEN '55'
					WHEN ([STATE_CODE] = 'WV') THEN '54'
					WHEN ([STATE_CODE] = 'WY') THEN '56'
					ELSE NULL
					END
GO

